env:
  browser: true
  commonjs: true
  es2021: true

settings:
  react:
    version: detect


extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:jest/recommended'

parserOptions:
  sourceType: module
  allowImportExportEverywhere: true
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12

plugins:
  - react
  - jest

rules:
  indent:
    - 1
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  react/react-in-jsx-scope: 0
  
